ERROR 2025-05-13 23:55:59,931 ai_helper 19228 24904 Ошибка при классификации продукта 'Вафли Черноморские Топ Спартак': '\n  "ingredient_type_id"'
Traceback (most recent call last):
  File "D:\BSUIR\Semester6\CourseWork\FoodBalancer\AppBackend\apps\core\barcode\ai_helper.py", line 86, in classify_product
    prompt = PRODUCT_CLASSIFICATION_PROMPT.format(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '\n  "ingredient_type_id"'
ERROR 2025-05-14 00:01:18,997 ai_helper 18764 29004 Ошибка при классификации продукта 'Вафли Черноморские Топ Спартак': '\n  "ingredient_type_id"'
Traceback (most recent call last):
  File "D:\BSUIR\Semester6\CourseWork\FoodBalancer\AppBackend\apps\core\barcode\ai_helper.py", line 86, in classify_product
    prompt = PRODUCT_CLASSIFICATION_PROMPT.format(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '\n  "ingredient_type_id"'
ERROR 2025-05-14 00:03:39,501 ai_helper 3920 29092 Ошибка при классификации продукта 'Вафли Черноморские Топ Спартак': Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}}
Traceback (most recent call last):
  File "D:\BSUIR\Semester6\CourseWork\FoodBalancer\AppBackend\apps\core\barcode\ai_helper.py", line 96, in classify_product
    response = self.client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BSUIR\Semester6\CourseWork\FoodBalancer\AppBackend\.venv\Lib\site-packages\openai\_utils\_utils.py", line 287, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\BSUIR\Semester6\CourseWork\FoodBalancer\AppBackend\.venv\Lib\site-packages\openai\resources\chat\completions\completions.py", line 925, in create
    return self._post(
           ^^^^^^^^^^^
  File "D:\BSUIR\Semester6\CourseWork\FoodBalancer\AppBackend\.venv\Lib\site-packages\openai\_base_client.py", line 1239, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BSUIR\Semester6\CourseWork\FoodBalancer\AppBackend\.venv\Lib\site-packages\openai\_base_client.py", line 1034, in request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}}
ERROR 2025-05-14 00:10:32,420 ai_helper 24668 17012 Ошибка при классификации продукта 'Вафли Черноморские Топ Спартак': Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\BSUIR\Semester6\CourseWork\FoodBalancer\AppBackend\apps\core\barcode\ai_helper.py", line 112, in classify_product
    classification = json.loads(result)
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\artem\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\artem\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\artem\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
